# Generated by Django 4.2.6 on 2023-12-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_skills", "0006_remove_hardskill_project_hardskill_card"),
        ("app_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_skills.hardskill",
                verbose_name="Website",
            ),
        ),
    ]
