# Generated by Django 4.2.6 on 2023-12-08 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projects", "0002_project_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="Separado por virgula ,",
                null=True,
                size=None,
                verbose_name="Tags",
            ),
        ),
    ]
