# Generated by Django 4.2.6 on 2023-12-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projects", "0006_project_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="icons",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
