# Generated by Django 4.2.6 on 2023-12-06 14:07

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição website",
                    ),
                ),
                (
                    "header_wellcome_title",
                    models.CharField(
                        default="Mensagem de boas-vindas",
                        max_length=255,
                        verbose_name="Mensagem de boas-vindas",
                    ),
                ),
                (
                    "header_profession",
                    models.CharField(
                        default="Profissão", max_length=255, verbose_name="Profissão"
                    ),
                ),
                (
                    "header_description",
                    models.TextField(
                        default="Descrição", max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "header_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo_header/%Y/%m/%d/",
                        verbose_name="Foto do cabeçalho",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Sobre Mim",
                        max_length=255,
                        verbose_name="Titulo - Sobre Mim",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="Minha história.", verbose_name="Minha historia"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo_perfil/%Y/%m/%d/",
                        verbose_name="Foto",
                    ),
                ),
                ("name", models.CharField(default="Luiz Santana", max_length=255)),
                ("email", models.EmailField(default="email@email.com", max_length=255)),
                (
                    "phone",
                    models.CharField(
                        default="879956080", max_length=16, verbose_name="Telefone"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        default=datetime.date(2023, 12, 6),
                        verbose_name="Data de Nascimento",
                    ),
                ),
                ("is_freelance", models.BooleanField(default=False)),
                (
                    "nationality",
                    models.CharField(
                        blank=True, default="Brasileira", max_length=80, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        help_text="Separado por virgula ,",
                        null=True,
                        size=None,
                        verbose_name="linguagem Faladas",
                    ),
                ),
                (
                    "historic",
                    models.JSONField(
                        default=list,
                        verbose_name="Historicos acadêmicos e profissionais",
                    ),
                ),
                ("skills", models.JSONField(default=list, verbose_name="Habilidades")),
                (
                    "github",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="https://github.com/",
                    ),
                ),
                (
                    "gitlab",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="https://gitlab.com/",
                    ),
                ),
                (
                    "stackoverflow",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="https://stackoverflow.com/",
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="https://linkedin.com/",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="https://facebook.com/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Ativo?"),
                ),
            ],
            options={
                "verbose_name": "website",
                "verbose_name_plural": "websites",
            },
        ),
    ]
