# Generated by Django 4.2.6 on 2023-12-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0003_website_card_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="card_skills",
            new_name="skills_card",
        ),
    ]
