# Generated by Django 4.2.6 on 2023-12-08 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0004_rename_card_skills_website_skills_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="birth_date",
            field=models.DateField(
                default=datetime.date(2023, 12, 8), verbose_name="Data de Nascimento"
            ),
        ),
    ]
