# Generated by Django 4.2.6 on 2023-12-08 15:00

import app.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0005_alter_website_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="header_photo",
            field=app.common.fields.ImageField(
                blank=True,
                null=True,
                upload_to="website/header/%Y/%m/%d/",
                verbose_name="Foto do cabeçalho",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="photo",
            field=app.common.fields.ImageField(
                blank=True,
                null=True,
                upload_to="website/perfil/%Y/%m/%d/",
                verbose_name="Foto",
            ),
        ),
    ]
