# Generated by Django 4.2.6 on 2023-12-10 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0006_alter_website_header_photo_alter_website_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="birth_date",
            field=models.DateField(
                default=datetime.date(2023, 12, 10), verbose_name="Data de Nascimento"
            ),
        ),
    ]
