# Generated by Django 4.2.6 on 2023-12-16 15:43

import app.common.fields
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0008_alter_website_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="address",
        ),
        migrations.RemoveField(
            model_name="website",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="website",
            name="content",
        ),
        migrations.RemoveField(
            model_name="website",
            name="email",
        ),
        migrations.RemoveField(
            model_name="website",
            name="header_description",
        ),
        migrations.RemoveField(
            model_name="website",
            name="header_photo",
        ),
        migrations.RemoveField(
            model_name="website",
            name="header_profession",
        ),
        migrations.RemoveField(
            model_name="website",
            name="header_wellcome_title",
        ),
        migrations.RemoveField(
            model_name="website",
            name="is_freelance",
        ),
        migrations.RemoveField(
            model_name="website",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="website",
            name="name",
        ),
        migrations.RemoveField(
            model_name="website",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="website",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="website",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="website",
            name="title",
        ),
        migrations.AddField(
            model_name="website",
            name="about",
            field=models.JSONField(default=dict, verbose_name="Cabeçalho da página"),
        ),
        migrations.AddField(
            model_name="website",
            name="header",
            field=models.JSONField(default=dict, verbose_name="Cabeçalho da página"),
        ),
        migrations.AlterField(
            model_name="website",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="github",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Github"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="gitlab",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Gitlab"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="linkedin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Linkedin"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="stackoverflow",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stackoverflow"
            ),
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        default="Mensagem de boas-vindas",
                        max_length=255,
                        verbose_name="Mensagem de boas-vindas",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        default="Profissão", max_length=255, verbose_name="Profissão"
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Descubra mais sobre mim...",
                        max_length=255,
                        verbose_name="Subtítulo",
                    ),
                ),
                (
                    "header_photo",
                    app.common.fields.ImageField(
                        blank=True,
                        null=True,
                        upload_to="website/header/%Y/%m/%d/",
                        verbose_name="Foto do cabeçalho",
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_website_header",
                        to="app_website.website",
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cabeçalho Website",
                "verbose_name_plural": "Cabeçalhos Websites",
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        default="Sobre Mim",
                        max_length=255,
                        verbose_name="Titulo - Sobre Mim",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="Minha história.", verbose_name="Minha historia"
                    ),
                ),
                (
                    "photo",
                    app.common.fields.ImageField(
                        blank=True,
                        null=True,
                        upload_to="website/perfil/%Y/%m/%d/",
                        verbose_name="Foto",
                    ),
                ),
                ("name", models.CharField(default="Luiz Santana", max_length=255)),
                ("email", models.EmailField(default="email@email.com", max_length=255)),
                (
                    "phone",
                    models.CharField(
                        default="879956080", max_length=16, verbose_name="Telefone"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data de Nascimento"
                    ),
                ),
                ("is_freelance", models.BooleanField(default=False)),
                (
                    "nationality",
                    models.CharField(
                        blank=True, default="Brasileira", max_length=80, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        help_text="Separado por virgula ,",
                        null=True,
                        size=None,
                        verbose_name="linguagem Faladas",
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_website_about",
                        to="app_website.website",
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cabeçalho Website",
                "verbose_name_plural": "Cabeçalhos Websites",
            },
        ),
    ]
