# Generated by Django 4.2.6 on 2023-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0010_alter_about_options_alter_header_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="website",
            name="github",
        ),
        migrations.RemoveField(
            model_name="website",
            name="gitlab",
        ),
        migrations.RemoveField(
            model_name="website",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="website",
            name="stackoverflow",
        ),
        migrations.AddField(
            model_name="website",
            name="contact",
            field=models.JSONField(default=dict, verbose_name="Dados para contato"),
        ),
    ]
