# Generated by Django 4.2.6 on 2023-12-17 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0011_remove_website_facebook_remove_website_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="email"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="whatsapp"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Github"
                    ),
                ),
                (
                    "gitlab",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Gitlab"
                    ),
                ),
                (
                    "stackoverflow",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stackoverflow",
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Linkedin"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_website_contact",
                        to="app_website.website",
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados para contato",
                "verbose_name_plural": "Dados para contato",
            },
        ),
    ]
