# Generated by Django 4.2.6 on 2023-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0012_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="facebook",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(
                default="email@gmail.com", max_length=255, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="github",
            field=models.CharField(
                default="gitlab.com", max_length=255, verbose_name="Github"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="gitlab",
            field=models.CharField(
                default="github.com", max_length=255, verbose_name="Gitlab"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="linkedin",
            field=models.CharField(
                default="linkedin.com", max_length=255, verbose_name="Linkedin"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="stackoverflow",
            field=models.CharField(
                default="stackoverflow.com",
                max_length=255,
                verbose_name="Stackoverflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="whatsapp",
            field=models.CharField(
                default="86999605077", max_length=255, verbose_name="whatsapp"
            ),
        ),
    ]
