# Generated by Django 4.2.6 on 2023-12-18 17:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=16)),
                ("subject", models.CharField(max_length=175)),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Mensagem"),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False, verbose_name="Mensagem Respondida?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato | Mensagem",
                "verbose_name_plural": "Contatos | Mensagens",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
