# Generated by Django 4.2.6 on 2023-12-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_skills", "0002_alter_hardskill_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hardskill",
            options={
                "ordering": ["order", "type"],
                "verbose_name": "Hard Skill",
                "verbose_name_plural": "Hard Skills",
            },
        ),
        migrations.AlterField(
            model_name="hardskill",
            name="type",
            field=models.CharField(
                choices=[
                    ("front_end", "FRONT-END"),
                    ("back_end", "BACK-END"),
                    ("mobile", "MOBILE"),
                    ("desktop", "DESKTOP"),
                    ("dev_ops", "DevOps"),
                ],
                default="back_end",
                verbose_name="Tipo Skill",
            ),
        ),
    ]
