# Generated by Django 4.2.6 on 2023-12-07 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0002_alter_website_birth_date"),
        ("app_skills", "0003_alter_hardskill_options_alter_hardskill_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardHardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número da ordem de exibição.",
                        verbose_name="Ordenação",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_website.website",
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Skill",
                "verbose_name_plural": "Card Skills",
            },
        ),
    ]
