# Generated by Django 4.2.6 on 2023-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_skills", "0004_cardhardskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardhardskill",
            name="name",
            field=models.CharField(
                help_text="FRONT-END, BACK-END, MOBILE...",
                max_length=100,
                verbose_name="Nome",
            ),
        ),
    ]
