# Generated by Django 4.2.6 on 2023-12-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_skills", "0005_alter_cardhardskill_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardskill",
            name="project",
        ),
        migrations.AddField(
            model_name="hardskill",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_skills.cardhardskill",
                verbose_name="Card Skill",
            ),
        ),
    ]
