# Generated by Django 4.2.6 on 2023-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_skills", "0006_remove_hardskill_project_hardskill_card"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardhardskill",
            options={
                "ordering": ["order"],
                "verbose_name": "Card Skill",
                "verbose_name_plural": "Card Skills",
            },
        ),
        migrations.AlterField(
            model_name="hardskill",
            name="time_experience",
            field=models.CharField(
                choices=[
                    ("_0_year_0_month", "INICIANDO ESTUDOS"),
                    ("_0_year_6_month", "6 MESES"),
                    ("_1_year_0_month", "1 ANO"),
                    ("_1_year_6_month", "1 ANO E 6 MESES"),
                    ("_2_year_0_month", "2 ANO"),
                    ("_2_year_6_month", "2 ANO E 6 MESES"),
                    ("_3_year_0_month", "3 ANO"),
                    ("_3_year_6_month", "3 ANO E 6 MESES"),
                    ("_4_year_0_month", "4 ANO"),
                    ("_5_year_0_month", "5 ANO"),
                    ("_6_year_0_month", "6 ANO"),
                    ("_7_year_0_month", "7 ANO"),
                    ("_8_year_0_month", "8 ANO"),
                    ("_9_year_0_month", "9 ANO"),
                    ("_10_year_0_month", "10 ANO OU MAIS"),
                ],
                default="_0_year_0_month",
                verbose_name="Tempo de experiência",
            ),
        ),
    ]
