# Generated by Django 4.2.6 on 2023-12-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_website", "0004_rename_card_skills_website_skills_card"),
        ("app_skills", "0007_alter_cardhardskill_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CardHardSkill",
            new_name="CardSkill",
        ),
        migrations.AlterModelOptions(
            name="cardskill",
            options={
                "ordering": ["order"],
                "verbose_name": "Cartão de Habilidades",
                "verbose_name_plural": "Cartões de Habilidades",
            },
        ),
    ]
