# Generated by Django 4.2.6 on 2023-12-06 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modificado em",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Curso ou Cargo",
                    ),
                ),
                (
                    "institution_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Instituição ou Empresa",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("professional", "EXPERIÊNCIAS PROFISSIONAIS"),
                            ("academic", "HISTÓRICO ACADÊMICO"),
                        ],
                        default="academic",
                        verbose_name="Tipo de ",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website",
                        to="app_website.website",
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico",
                "verbose_name_plural": "Historicos",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricAcademic",
            fields=[],
            options={
                "verbose_name": "Historico Academico",
                "verbose_name_plural": "Historicos Academicos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_historic.historic",),
        ),
        migrations.CreateModel(
            name="HistoricProfessional",
            fields=[],
            options={
                "verbose_name": "Historico Profissional",
                "verbose_name_plural": "Historicos Profissional",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_historic.historic",),
        ),
    ]
