# Generated by Django 4.2.6 on 2023-12-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_historic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historic",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
    ]
